project:
  type: website
  output-dir: docs

website:
  title: "AlphaFold at Sydney"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Sessions"
        menu:
        - text: "Introduction to AlphaFold"
          href: notebooks/01_alphafold.html
        - text: "Introduction to HPC"
          href: notebooks/02_hpc.html
        - text: "Running AlphaFold on Artemis"
          href: notebooks/03_artemis.html
        - text: "Running AlphaFold with Docker/Singularity"
          href: notebooks/04_singularity.html
        - text: "Running AlphaFold on NCI Gadi"
          href: notebooks/05_nci.html
        - text: "Running AlphaFold on Cloud"
          href: notebooks/06_aws.html
        - text: "Running AlphaFold on Google Colab"
          href: notebooks/07_colabfold.html
        - text: "Running AlphaFold on Biocommons Galaxy"
          href: notebooks/08_biocommons.qmd

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


